survey-salesforce/salesforce-app/src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <description>Option(used for Multitext questions)</description>
        <label>Option</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Device__c.object
<CustomObject>
    <label>Device</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of the option within the option group</description>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/ScoringGroup__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Scoring Groups</relationshipLabel>
        <relationshipName>Scoring_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Scoring Group</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scoring Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interviewee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Surveyor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Submissions (Surveyor)</relationshipLabel>
        <relationshipName>SubmissionObtained</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>endDate__c</fullName>
        <label>endDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>gps_x__c</fullName>
        <label>gps x</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>gps_y__c</fullName>
        <label>gps y</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>startDate__c</fullName>
        <label>startDate</label>
        <type>DateTime</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/classes/SurveyCsvExport.cls
public with sharing class SurveyCsvExport {

    private static final String NO_DATA_MSG='No data available for this survey';
    private static final String HEADER_SUBMISSION_DATA= '"startDate","endDate","Date","Device","gps_x","gps_y","Interviewee","Surveyor",';
    private static final String ERR_EXPECTED_TEXT_FOUND_ELEMENT = 'Error parsing submission XML: Expected text node, found element';
    public String surveyId {get;set;}
    /*class that represents a Csv File ,used to manage
    the construction of a CSV file*/

    public class csvFile{
        public String headerRow;
        public List<String> columns= new List<String>();
        public List<String> scoringGroupsColumns = new List<String>();
        public Map<Id,String> answerRow = new Map<Id,String>();

        //set the header row for the csv file,only need to be called once
        public void setHeader(List<Question__c> surveyQuestions,String SubmissionFields){
            headerRow = SubmissionFields;
            // Questions query does not fetch sections and static questions, so I know all questions are to be output.
            for(Question__c question:surveyQuestions){
                headerRow += '"' +  question.Name + '",';
                Columns.add(question.Name);
            }
        }

        //set a Row for a Submission with their answers
        //Precondition: setHeader must be previosly called to generate Columns.
        public void setRow(Submission__c submission,Map<String,String> AnswerByQuestionName){
            //create a String variable that keeps the csv row
            String rowString = '"'
                + submission.startDate__c + '","'
                + submission.endDate__c + '","'
                + submission.Date__c + '","'
                + submission.Device__c +'","'
                + (submission.gps_x__c != null ? String.valueOf(submission.gps_x__c) : '') + '","'
                + (submission.gps_y__c != null ? String.valueOf(submission.gps_y__c) : '') + '","'
                + (submission.interviewee__c != null ? submission.Interviewee__r.Name : '') + '","'
                + submission.Surveyor__r.Name +'",';
            for (String col:Columns){
                rowString += '"' + (AnswerByQuestionName.get(col) != null ? AnswerByQuestionName.get(col) : '') + '",';
            }
            AnswerRow.put(Submission.Id,rowString);
        }
        //Add the score data in a submission row
        public void setRowScores(Submission__c submission,Map<String,SubmissionScore__c> scoreByScoreGroup){

            for (String col:scoringGroupsColumns){
                answerRow.put(
                    submission.Id,
                    answerRow.get(submission.Id) + '"' + (scoreByScoreGroup.get(col)!=null ? String.valueOf(scoreByScoreGroup.get(col).TotalScore__c) : '') + '",');
            }

        }

        public String getString(){
            String csv = headerRow + '\n';
            for (String row:answerRow.values()){
                csv += row +'\n';
            }
            return csv;
        }

        public void setScoringGroupsColumns(List<ScoringGroup__c> scoringGroups){
            for(ScoringGroup__c sg:scoringGroups){
                    headerRow += '"'+ sg.Caption__c + '",';
                    scoringGroupsColumns.add(sg.Caption__c);
    }
        }

    }


    public String getCsvString(){
        surveyId = ApexPages.currentPage().getParameters().get('surveyid');
        String stringSubmissions = ApexPages.currentPage().getParameters().get('selectedSurveysAnswerId');
        List<Submission__c> submissionsToExport;

        if (stringSubmissions!=null && stringSubmissions!=''){

            List<String> answerIdsParam = stringSubmissions.split(',',0);
            submissionsToExport =  [select Id,survey__c,
                                            startDate__c ,
                                            endDate__c,
                                            Date__c,
                                            Device__c,
                                            gps_x__c,
                                            gps_y__c,
                                            surveyor__c, surveyor__r.Name,
                                            interviewee__c, interviewee__r.Name
                                            from Submission__c where Id in :answerIdsParam];
            surveyId = (SubmissionsToExport.size()>0)? SubmissionsToExport[0].survey__c: null;

        }else if (surveyId!=null){
            submissionsToExport = [select Id,survey__c,
                                            startDate__c ,
                                            endDate__c,
                                            Date__c,
                                            Device__c,
                                            gps_x__c,
                                            gps_y__c,
                                            surveyor__c, surveyor__r.Name,
                                            interviewee__c, interviewee__r.Name
                                            from Submission__c where survey__c = :surveyId];
        }
        return exportToCsv(surveyId,SubmissionsToExport);
    }

    //Method to convert Survey answer xml to a CSV file for further export
    public String exportToCsv(Id surveyId,Submission__c[] submissionsToExport){
        //Survey Questions and responses
        List<Answer__c> surveyAnswers = [
            SELECT Id,Value__c,Question__r.Name,Option__r.Name,Option__r.Caption__c,Question__r.Type__c,Submission__c
            FROM Answer__c
            WHERE Submission__c IN :submissionsToExport
            ORDER BY Submission__c, Question__r.Parent__r.Position__c, Question__r.Position__c, Option__r.Position__c];
        List<Question__c> surveyQuestions = [
            SELECT Id,Name,Caption__c,Type__c
            FROM Question__c
            WHERE Survey__c = :surveyId AND Type__c NOT IN (:QuestionType.QUESTION_SECTION, :QuestionType.QUESTION_STATIC)
            ORDER BY Parent__r.Position__c, Position__c];
        //survey Scoring
        List<ScoringGroup__c> scoringGroups = [SELECT Id, Caption__c FROM ScoringGroup__c WHERE survey__c = :surveyId ORDER BY Id];

        // Save a map of Submission Id -> Scoring Group Id -> Score
        List<submissionScore__c> scores = [SELECT Id, TotalScore__c,Submission__c,ScoringGroup__c,ScoringGroup__r.Caption__c
                                           FROM SubmissionScore__c
                                           WHERE Submission__c in :SubmissionsToExport
                                           ORDER BY Submission__c, ScoringGroup__c];


        csvFile csv = new CsvFile();
        //generate the header row of the csv

        csv.setHeader(surveyQuestions,HEADER_SUBMISSION_DATA);
        csv.setScoringGroupsColumns(scoringGroups);
        //generate each submission row
        for (Submission__c sub:submissionsToExport){
            Map<String,String> AnswerByQuestionName = new Map<String,String>();
            Map<String,SubmissionScore__c> ScoreByScoreGroup = new Map<String,SubmissionScore__c>();
            //generate the map for each submission,retriving the first element of the list adding it to the map
            //and removing it,stop to loop when the first element doesn't belong to the survey

            while(!surveyAnswers.isEmpty() && surveyAnswers[0].Submission__c == sub.Id){
                //if the answer belongs to the same column separate the values with ; (checkbox case)
                AnswerByQuestionName.put(
                    surveyAnswers[0].Question__r.Name,
                    (AnswerByQuestionName.get(surveyAnswers[0].Question__r.Name) != null
                        ? AnswerByQuestionName.get(surveyAnswers[0].Question__r.Name) + ';'
                        : ''
                        ) + surveyAnswers.remove(0).Value__c);
            }

            csv.setRow(sub,AnswerByQuestionName);
            //generate the map for each scoring
            while(!scores.isEmpty() && scores[0].Submission__c == sub.Id){
                String groupName = scores[0].ScoringGroup__r.Caption__c;
                ScoreByScoreGroup.put(groupName,scores.remove(0));
            }
            csv.setRowScores(sub,ScoreByScoreGroup);
        }

        return csv.getString();
    }
}