survey-salesforce/salesforce-app/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>mobilesurveys_Id__c</fullName>
        <externalId>true</externalId>
        <label>mobilesurveys Id</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>mobilesurveys_Password__c</fullName>
        <label>Password</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>mobilesurveys_Username__c</fullName>
        <label>Username</label>
        <length>64</length>
        <type>Text</type>
    </fields>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Device__c.object
<CustomObject>
    <fields>
        <fullName>IMEI__c</fullName>
        <externalId>true</externalId>
        <label>IMEI</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Device</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of the option within the option group</description>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/ScoreValue__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ScoringGroup__c</fullName>
        <label>Scoring Group</label>
        <referenceTo>ScoringGroup__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Score Value</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>Score Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/ScoringGroup__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Scoring Groups</relationshipLabel>
        <relationshipName>Scoring_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Scoring Group</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scoring Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Device__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Device</label>
        <referenceTo>Device__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interviewee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploaded</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SurveyVersion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SurveyVersion</label>
        <referenceTo>SurveyVersion__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Surveyor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Submissions (Surveyor)</relationshipLabel>
        <relationshipName>SubmissionObtained</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>endDate__c</fullName>
        <label>endDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>gps_x__c</fullName>
        <label>gps x</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>gps_y__c</fullName>
        <label>gps y</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>startDate__c</fullName>
        <label>startDate</label>
        <type>DateTime</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>InterviewMapField__c</fullName>
        <description>Indicates which field maps with the interviewee field of the survey</description>
        <label>Interviewee Map Field</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SurveyVersion</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SurveyVersions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/classes/SurveyCsvExportTest.cls
@isTest
private class SurveyCsvExportTest {


    /*Method to prepare the data for performing a test.inserts survey
    question and their options */
    public static Contact createContactWithCredentials(String user,String pass){
        Contact newContact = new Contact( LastName='Robert',
                            mobilesurveys_Username__c=user,
                            mobilesurveys_Password__c=pass);

        insert newContact;
        return [select Id, Name from Contact where Id = :newcontact.Id];
    }

    class TestData{
        public String[] xml;
        public String expected;
        public Id surveyId;
    }

    public static TestData PrepareData(Contact loggedContact){
    //PREPARING THE DATA FOR THE TEST

        Survey__c survey = new Survey__c(Name='Survey',InterviewMapField__c='mobileSurveys_Id__c');
        insert survey;
        Question__c qSection = new Question__c(Survey__c=survey.Id, Name='qsect', Caption__c= 'SECTIONNN',Type__c = QuestionType.QUESTION_SECTION);
        insert qSection;
        Question__c q0 = new Question__c(Parent__c= qSection.Id,Survey__c=survey.Id, Name='qstat', Caption__c= 'Static Content',Type__c = QuestionType.QUESTION_STATIC,Position__c=1);
        Question__c q1 = new Question__c(Parent__c= qSection.Id,Survey__c=survey.Id, Name='qshrt', Caption__c= 'Age',Type__c = QuestionType.QUESTION_TEXT_SHORT,Position__c=2);
        Question__c q2 = new Question__c(Parent__c= qSection.Id,Survey__c=survey.Id, Name='qlong', Caption__c= 'Last Name',Type__c = QuestionType.QUESTION_TEXT_LONG,Position__c=3);
        Question__c q3 = new Question__c(Parent__c= qSection.Id,Survey__c=survey.Id, Name='qchkx', Caption__c= 'select some',Type__c = QuestionType.QUESTION_CHECKBOX,Position__c=4);
        Question__c q4 = new Question__c(Parent__c= qSection.Id,Survey__c=survey.Id, Name='qnum', Caption__c= 'number',Type__c = QuestionType.QUESTION_NUMBER,Position__c=5);
        Question__c q5 = new Question__c(Parent__c= qSection.Id,Survey__c=survey.Id, Name='qdate', Caption__c= 'date',Type__c = QuestionType.QUESTION_DATE,Position__c=6 );
        Question__c q6 = new Question__c(Parent__c= qSection.Id,Survey__c=survey.Id, Name='qdateTime', Caption__c= 'dateTime',Type__c = QuestionType.QUESTION_DATETIME,Position__c=7);
        insert new Question__c[]{q0,q1,q2,q3,q4,q5,q6};

        Option__c opA = new Option__c(Name= 'opcion A',Caption__c='opcion A',Question__c = q3.Id,Position__c=1);
        Option__c opB = new Option__c(Name= 'opcion B',Caption__c='opcion B',Question__c = q3.Id,Position__c=2);
        List<Option__c> options= new List<Option__c>{opA,opB};
        insert options;
        Contact c = new Contact(LastName = 'Robert', mobileSurveys_Id__c='ab12');
        insert c;
        c = [select Id, Name, mobileSurveys_Id__c from Contact where Id = :c.Id];
        qSection = [select name from Question__c where id=:qSection.Id][0];

        ScoringGroup__c sGroup = new ScoringGroup__c(Caption__c = 'score1', Survey__c = survey.Id);
        insert sGroup;
        ScoreValue__c sValue1 = new ScoreValue__c(Option__c = opA.Id, ScoringGroup__c = sGroup.Id, Value__c = 1);
        ScoreValue__c sValue2 = new ScoreValue__c(Option__c = opB.Id, ScoringGroup__c = sGroup.Id, Value__c = 2);
        insert new ScoreValue__c[]{sValue1, sValue2};
        //Clean Devices and add new one
        List<Device__c> allDevices = [SELECT Id FROM Device__c Where Id!=null];
        delete allDevices;
        Device__c usedDevice = new Device__c(Name='24245215234',Imei__c='24245215234',Status__c='Active');
        insert usedDevice;
        SurveyVersion__c surveyVersion = [select Status__c from SurveyVersion__c where Survey__c =:survey.Id];
        surveyVersion.Status__c = 'Published';
        update surveyVersion;
        TestData result = new TestData();
        //XML 1
        result.xml = new String[]{};
        for(integer i=0;i<3;i++){
            result.xml.add('<?xml version=\'1.0\' ?><'+ survey.Name + ' id="' + survey.Id + '">'+
            '<start>2012-02-14T19:23:53.463</start>'+
            '<end>2012-02-14T19:24:40.816</end>'+
            '<today>2012-02-14</today>'+
            '<deviceid>356402040028589</deviceid>'+
            '<subscriberid >' + c.mobileSurveys_Id__c + '</subscriberid >'+
            '<simid />'+
            '<phonenumber />'+
            '<' + qSection.Name + '>' +
                '<'+ q0.Name +' />' +
                '<'+ q1.Name +'>2'+ i +'</'+ q1.Name +'>'+
                '<'+ q2.Name +'>Martin</'+ q2.Name +'>'+
                '<'+ q3.Name +'>' + opA.Id + ' ' + OpB.Id + ' </'+ q3.Name +'>'+
                '<'+ q4.Name + '>' + 10 + '</' + q4.Name + '>' +
                '<'+ q5.Name + '>' + '2012-02-14' + '</' + q5.Name + '>' +
                '<'+ q6.Name + '>' + '2012-02-14T19:23:53.463' + '</' + q6.Name + '>' +
            '</' + qSection.Name + '>' +
        '</'+ survey.Name + '>');
        }
        result.expected =
        '"startDate","endDate","Date","Device","gps_x","gps_y","Interviewee","Surveyor",' +
        '"' + q1.Name + '",' +
        '"' + q2.Name + '",' +
        '"' + q3.Name + '",' +
        '"' + q4.Name + '",' +
        '"' + q5.Name + '",' +
        '"' + q6.Name + '",' +
        '"' + sGroup.Caption__c + '",' + '\n' +
        '"' + DateTime.valueOf('2012-02-14 19:23:53') + '",' + '"' + DateTime.valueOf('2012-02-14 19:24:40') + '",' +
        '"2012-02-14 00:00:00",' +
        '"' + usedDevice.Id +'","","","'+ c.Name + '","' + loggedContact.Name + '","'+ '20",'+
        '"Martin","' + opA.Caption__c + ';' + OpB.Caption__c + '",' + '"10",'+ '"2012-02-14",'+ '"2012-02-14 19:23:53.463",' + '"3",' + '\n';

        result.surveyId = survey.Id;
        return result;
    }

    private static void loadContactCredentialsOnPage(String user, String pass, String imei){
        ApexPages.currentPage().getHeaders().put('user',user);
        ApexPages.currentPage().getHeaders().put('pass',pass);
        ApexPages.currentPage().getHeaders().put('imei',imei);
    }

    /*Test for a single case of csv Creation*/
     static testMethod void exportAllSubmissions() {
         //PERFORMING THE TEST
         PageReference pr = Page.Submission;
        Test.setCurrentPage(pr);
        Contact loggedContact = createContactWithCredentials('user1','thePass');
        TestData data = prepareData(loggedContact);
        ApexPages.currentPage().getHeaders().put('surveyAnswer',data.xml[0]);
        ApexPages.currentPage().getParameters().put('Last','true');

        //create a valid user for submission
        loadContactCredentialsOnPage('user1','thePass','24245215234');

        ServicesController sc = new ServicesController();
        sc.submit();
        SurveyCsvExport csvCreator = new SurveyCsvExport();
        PageReference downpagePage = Page.downloadCsv;
        Test.setCurrentPage(downpagePage);
        ApexPages.currentPage().getParameters().put('surveyId',data.surveyId);

        system.assertEquals(data.expected,csvCreator.getCsvString());

     }

     static testMethod void exportSelectedSubmissions() {
         //PERFORMING THE TEST
        PageReference pr = Page.Submission;
        Test.setCurrentPage(pr);
        //clean users and create a valid user for submission
        delete ([select Id from Contact where mobilesurveys_Username__c= 'user1']);

        Contact loggedContact = createContactWithCredentials('user1','thePass');
        TestData data = prepareData(loggedContact);
        ApexPages.currentPage().getParameters().put('Last','true');


        loadContactCredentialsOnPage('user1','thePass','24245215234');

        // Submit three times, but I'm only going to export two of them
        ServicesController sc = new ServicesController();
        for(string s:data.xml){
            ApexPages.currentPage().getHeaders().put('surveyAnswer',s);
            sc.submit();
        }
        Submission__c[] submissions = [select Id,survey__c,
                                            startDate__c ,
                                            endDate__c,
                                            Date__c,
                                            Device__c,
                                            gps_x__c,
                                            gps_y__c,
                                            surveyor__c, surveyor__r.Name,
                                            interviewee__c, interviewee__r.Name
                                            from Submission__c where Survey__c = :data.surveyId];
        system.assertEquals(3, submissions.size());

        SurveyCsvExport csvCreator = new SurveyCsvExport();
        PageReference downpagePage = Page.downloadCsv;
        Test.setCurrentPage(downpagePage);
        ApexPages.currentPage().getParameters().put('selectedSurveysAnswerId',submissions[0].Id + ',' + submissions[1].Id);

        // Assert the result only has three lines (1 header + 2 rows)
        system.assertEquals(3, csvCreator.getCsvString().split('\n',0).size());
     }
}