survey-salesforce/salesforce-app/src/objects/ContactGroup__c.object
<CustomObject>
    <description>This is a group where a contacts and surveys can be assigned. After that the surveys in the group will be distributed to the users in the group.</description>
    <fields>
        <fullName>MemberCount__c</fullName>
        <description>Show the count of members in the group</description>
        <label>Member Count</label>
        <summaryForeignKey>ContactGroupMember__c.ContactGroup__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates whether the Group is active or inactive</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/ContactGroupSurveyAssignment__c.object
<CustomObject>
    <description>Junction object for many to many relationship between Survey and Contact Group objects</description>
    <fields>
        <fullName>ContactGroup__c</fullName>
        <label>Contact Group</label>
        <referenceTo>ContactGroup__c</referenceTo>
        <relationshipName>ContactGroupSurveyAssignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Contact Group Survey Assignment</relationshipLabel>
        <relationshipName>Contact_Group_Survey_Assignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Assigned Survey</label>
    <nameField>
        <displayFormat>CGSA-{00000000}</displayFormat>
        <label>Contact Group Survey Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/classes/SurveyGroupAssignmentController.cls
public with sharing class SurveyGroupAssignmentController {
	public ContactGroup[] groupsList{get;set;}
	public boolean showDetails{get;set;}
	public string groupIdToDisplay{get;set;}
	public boolean missingId{get;set;}
	public String surveyName{get;set;}
	private string surveyId;
	Set<Id> isSelectedforthisversion;
	public SurveyGroupAssignmentController(){
		missingId = false;
		surveyId = Apexpages.currentPage().getParameters().get('id');
		if(surveyId != null){
			List<Survey__c> currentSurv = [SELECT Name FROM Survey__c WHERE Id=:surveyId];
			surveyName =  currentSurv.size() >0 ? currentSurv[0].Name : '';
			isSelectedforthisversion = new Set<Id>();
			for(ContactGroupSurveyAssignment__c SurveyAssignation :[SELECT ContactGroup__c,Id FROM ContactGroupSurveyAssignment__c WHERE Survey__c =: surveyId]){
				isSelectedforthisversion.add(SurveyAssignation.ContactGroup__c);
			}
			groupsList = new ContactGroup[]{};
			for (ContactGroup__c cG:[SELECT Name,MemberCount__c,Id FROM ContactGroup__c WHERE Status__c ='Active']){
				boolean selected = isSelectedforthisversion.contains(cG.Id);
				groupsList.add(new ContactGroup(cG,selected));
			}
			showDetails = false;
		}else{
			missingId = true;
			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'Missing Id parameter.');
			ApexPages.addMessage(myMsg);
		}
	}
	public class ContactGroup{
		public string Name{get{return cGroup.Name;}}
		public string Id{get{return cGroup.Id;}}
		public integer Members{get{return integer.valueof(cGroup.MemberCount__c);}}
		public boolean isSelected{get;set;}
		private ContactGroup__c cGroup;
		public ContactGroup(ContactGroup__c contactGroup,boolean selected){
			cGroup = contactGroup;
			isSelected = selected;
		}
	}
	public void ShowDetails(){
		showDetails = true;
	}
	public void HideDetails(){
		showDetails = false;
	}
	public PageReference Save(){
		ContactGroupSurveyAssignment__c[] groupsAssignmentToSave = new ContactGroupSurveyAssignment__c[]{};
		for(ContactGroup cG:groupsList){
			if(cG.isSelected == true){
				groupsAssignmentToSave.add(new ContactGroupSurveyAssignment__c(ContactGroup__c = cG.Id,Survey__c = surveyId));
			}
		}

		//Delete all the preview Assignments for this survey, then insert all new assignments.
		delete [SELECT Id FROM ContactGroupSurveyAssignment__c WHERE Survey__c =: surveyId];
		insert groupsAssignmentToSave;

		return Page.SurveyManager;
	}
}