survey-salesforce/salesforce-app/src/objects/LicenseSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To block or enable functionality in the client package . Indicates whether a function is enable or if there is a limit to use it.</description>
    <fields>
        <fullName>PPI_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PPI_Editable</label>
        <type>Checkbox</type>
    </fields>
    <label>LicenseSettings</label>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <description>This is the alias of the Survey</description>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Close_Message__c</fullName>
        <defaultValue>&quot;Thank you for taking the time to complete this survey!&quot;</defaultValue>
        <label>Message After Submission</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Gps_Location_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>GPS Capture</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gps_ShowMap__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GPS Show Map</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InterviewMapField__c</fullName>
        <description>Indicates which field maps with the interviewee field of the survey</description>
        <label>Interviewee Map Field</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the survey is a PPI Survey</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Saving_XForm__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used only when saving an XForm to avoid the deletion of the XForm in the CleanXForm trigger</description>
        <label>Saving XForm</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>XForm_Status__c</fullName>
        <description>XForm status indicates if the version has an xform and if it has customizations</description>
        <label>XForm Status</label>
        <picklist>
            <picklistValues>
                <fullName>NONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEFAULT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CUSTOM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/classes/XFormEditor.cls
public with sharing class XFormEditor {

    public Attachment actual_doc{ get; set; }
    public String body_actual_doc_val {get; set;}
    public String save_type {get;set;}
    public String Message{get; set; }
    public Survey__c survey {get;set;}
    public boolean hasErrors {get;set;}
    public boolean isEditable {get;set;}

    public XFormEditor(){}

    // This method shows the document related to the selected Survey in a separate page.
    public PageReference editXForm(){
        hasErrors = false;
        PageReference pg = new PageReference('/apex/SurveyManager');
        Id auxSurveyId = Apexpages.currentPage().getParameters().get('surveyId');

        if( auxSurveyId != null ){
            List<Survey__c> listSur = [select Name,Alias__c,Id, isPPI__c, Status__c,Gps_Location_Enabled__c, Close_Message__c,InterviewMapField__c, Gps_ShowMap__c From Survey__c where Id = :auxSurveyId];
            if( listSur != null && !listSur.isEmpty()) {
                survey = listSur[0];
                //-------------------------------------------------------        
                //URL License Control, can't execute code without licence permission
                LicenseSettings__c license = C.getLicense();
                if( !license.PPI_Editable__c && survey.IsPPI__c )
                    throw new C.LicenseException(system.label.SYSTEM_ERR_NOLICENSEPERMISSION);
                //--------------------------------------------------------
                

                    isEditable = (survey.Status__c == 'DRAFT');
                    List<Attachment> listDoc = [select Id, Body from Attachment where ParentId = :survey.Id and Name = :XformCreator.XFORM_ATTACHMENT ];

                    //if the document does not exist, creates a new one
                    if( listDoc == null || listDoc.isEmpty()){
                        new XFormCreator().createDocument(survey);
                        listDoc = [select Id, Body from Attachment where ParentId = :survey.Id and Name = :XformCreator.XFORM_ATTACHMENT ];
                    }

                    this.actual_doc = listDoc[0];
                    Blob blobDoc = this.actual_doc.Body;
                    String docBodyStr = blobDoc.toString();
                    this.Message = docBodyStr;
                    pg = null;
            }
        }
        return pg;
    }

    // saves changes. if it has an error, stays in the page and displays it. if it is a "save" return to survey manager, if it is a "quicksave" stays in the page
    public PageReference save () {

        if(body_actual_doc_val != null){
            this.actual_doc.Body = Blob.valueof(body_actual_doc_val);
            update this.actual_doc;

            //update the XForm Status in the version
            List<Survey__c> listSur = [select Id, XForm_Status__c, Saving_XForm__c From Survey__c where Id = :this.actual_doc.ParentId];
            if( listSur != null && !listSur.isEmpty()) {
                Survey__c survey = listSur[0];
                survey.XForm_Status__c = 'CUSTOM';
                survey.Saving_XForm__c = true;
                update survey;
            }

            hasErrors = false;
            if (this.save_type == 'save') return Page.SurveyManager;
        }
        return null;
    }

    //goes back to survey manager
    public PageReference cancel(){
        return Page.SurveyManager;
    }


}