survey-salesforce/salesforce-app/src/objects/LicenseSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To block or enable functionality in the client package . Indicates whether a function is enable or if there is a limit to use it.</description>
    <fields>
        <fullName>PPI_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PPI_Editable</label>
        <type>Checkbox</type>
    </fields>
    <label>LicenseSettings</label>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PPIScore__c</fullName>
        <description>Progress Out Of Poverty Index Score for this option.</description>
        <label>PPI Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of the option within the option group</description>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrentTime__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set date of the day and current time(take from device) as initial value</description>
        <label>Current Time</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DoAfter__c</fullName>
        <label>DoAfter</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DoBefore__c</fullName>
        <label>DoBefore</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Hint__c</fullName>
        <description>A hint for the question</description>
        <label>Hint</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Maximum__c</fullName>
        <label>Maximum</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum__c</fullName>
        <label>Minimum</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this question must be answered before moving to the next question</description>
        <inlineHelpText>Check if this question must be answered before moving to the next question</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SamePage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>All questions of a section show on same page</description>
        <label>SamePage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SkipLogicBehavior__c</fullName>
        <label>SkipLogicBehavior</label>
        <picklist>
            <picklistValues>
                <fullName>Show</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hide</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SkipLogicOperator__c</fullName>
        <label>SkipLogicOperator</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Any</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/ScoreValue__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ScoringGroup__c</fullName>
        <label>Scoring Group</label>
        <referenceTo>ScoringGroup__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Score Value</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>Score Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/ScoringGroup__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Scoring Groups</relationshipLabel>
        <relationshipName>Scoring_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Scoring Group</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scoring Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the survey is a PPI Survey</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/classes/SurveyScoringController.cls
public with sharing class SurveyScoringController {

    public Survey__c survey{get; set;}                                  // Actual survey.
    public BuilderQuestion[] questions = new BuilderQuestion[]{};
    public List<ScoringGroup> listGroups = new List<ScoringGroup>{};      // Actual list of custom ScoringGroup.
    public List<ScoringValue> listScoreValues = new List<ScoringValue>{}; // Actual list of custom ScoringValues.
    public String scoringGroupStr {get; set;}                             //JSON string passed from the page with the group data.
    public String scoringValuesJson {get; set;}                           //JSON string passed from the page with the Score values data.
    public String continueAfterwards {get;set;}                           //String that decides if should stay in the page (quick save) or continue
    public boolean errorGroup = false;                                    // True if fails saving Groups.
    public boolean errorValues = false;                                   // True if fails saving Scoring values.

    public String getQuestions()      { return JSON.serialize(questions); }
    public String getListGroups()     { return JSON.serialize(listGroups); }
    public String getListScoreValues(){ return JSON.serialize(listScoreValues); }
    
    public final string PPI_ID = 'PPI';
    private final string PPI_LABEL = 'Progress out of poverty index';
    /*
    *    Class constructor
    */
    public SurveyScoringController (ApexPages.StandardController stdController) {
        this.survey = (Survey__c)stdController.getRecord();
        this.survey = [select Id,Name,isPPI__c,LastModifiedDate FROM Survey__c WHERE Id=:survey.id limit 1];
        
        // Obtain all questions and their options, for this survey.
        for(Question__c q: [Select Id, Name, Type__c, Parent__c, Caption__c, Hint__c, Position__c,
                            Minimum__c, Maximum__c, DoBefore__c, DoAfter__c, Required__c,
                            SkipLogicBehavior__c, SkipLogicOperator__c, CurrentTime__c, SamePage__c
                            From Question__c Where Survey__c = :survey.Id order by Position__c]){
            questions.add( new BuilderQuestion(q) );
        }

        for(Option__c o: [Select Id, Name, Position__c,Caption__c, Question__c, PPIScore__c
                          From Option__c Where Question__r.Survey__c = :survey.Id order by Position__c]){
            BuilderQuestion bq = findQuestion(o.Question__c);
            bq.options.add( new BuilderQuestion.Option(o) );

        }
        if(this.survey.isPPI__c){
            listGroups.add(new ScoringGroup(PPI_ID,PPI_LABEL));
            for(Option__c o: [Select Id, Name, Position__c,Caption__c, Question__c, PPIScore__c
                          From Option__c Where Question__r.Survey__c = :survey.Id order by Position__c]){
                listScoreValues.add(new ScoringValue(string.valueof(o.PPIScore__c),string.valueof(o.Id),PPI_ID));
            }
        }
        for(ScoringGroup__c sg : [select Id, Caption__c from ScoringGroup__c where Survey__c = :this.survey.Id]){
            ScoringGroup newScoring = new ScoringGroup(sg);
            listGroups.add(newScoring);
        }


        for(ScoreValue__c sv : [select Id, Value__c, Option__c, ScoringGroup__r.Caption__c
                                from ScoreValue__c where ScoringGroup__r.Survey__c = :this.survey.Id order by Id]){
            ScoringValue newScoreValue = new ScoringValue(sv, sv.ScoringGroup__r.Caption__c);
            listScoreValues.add(newScoreValue);
        }
    }
    //-------------------------------------------------------        
    //URL License Control, can't execute code without licence permission
    public PageReference checkLicense(){
       LicenseSettings__c license = C.getLicense();
       if( !license.PPI_Editable__c && this.survey.IsPPI__c )
            throw new C.LicenseException(system.label.SYSTEM_ERR_NOLICENSEPERMISSION);
       return null; 
    }
    //--------------------------------------------------------
    
    // Find a question on the list by it's id
    private BuilderQuestion findQuestion(String id) {
        BuilderQuestion questionReturn = null;
        for (BuilderQuestion q : questions){
            if (q.id == id){
                questionReturn = q;
            }
        }
        return questionReturn;
    }

    // Called from the page when clicking "Save and continue".
    public PageReference saveScoring() {

        PageReference pg = null;
        Survey__c dummySurvey = [select Id, Status__c, LastModifiedDate from Survey__c where Id = :this.survey.Id limit 1];
        if(dummySurvey.LastModifiedDate != survey.LastModifiedDate){
            ApexPages.message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, system.Label.BUILDER_ERR_CONCURRENTSAVE);
            ApexPages.addMessage(myMsg);
        }else if(dummySurvey.Status__c != 'Draft'){
            ApexPages.message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, system.label.BUILDER_ERR_SURVEYALREADYPUBLISHED);
            ApexPages.addMessage(myMsg);
        }else {
            deleteRelatedScoring();

            // Creates groups.
            if( this.scoringGroupStr != ''){
                JSONParser parserGroups = JSON.createParser(this.scoringGroupStr);
                List<ScoringGroup> customGroups = parserScoringGroup(parserGroups);
                List<ScoringGroup__c> savedGroups = saveGroups(customGroups);

                if (this.errorGroup) {
                    ApexPages.message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'An error ocurrs while saving Score group, check group data');
                    ApexPages.addMessage(myMsg);
                }
                else  {
                    // Creates score values
                    JSONParser parserValue = JSON.createParser(this.scoringValuesJson);
                    List<ScoringValue> scoringValues = parserScoringValues(parserValue);
                    map<String, Id> mapNameId = getMapNameIdGroups(savedGroups);
                    // Saves data
                    saveScoringValues(scoringValues, mapNameId);

                    if(this.errorValues){
                        ApexPages.message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'An error ocurrs while saving Score values, check scoring values');
                        ApexPages.addMessage(myMsg);
                    }else{
                        if (this.continueAfterwards == 'true'){
                            pg = this.survey.IsPPI__c ? Page.LookupTables : Page.SurveyQuestionLogic;
                            pg.getParameters().put('id', this.survey.Id);
                        }
                        //Update Survey
                        update survey;
                        this.survey = [select Id,Name,isPPI__c,LastModifiedDate FROM Survey__c WHERE Id=:survey.id limit 1];
                    }
                }
            }
        }
        return pg;
    }

    public void deleteRelatedScoring(){
        List<ScoringGroup__c> groupToDelete = [select Id from ScoringGroup__c where Survey__c = :this.survey.Id];
        delete groupToDelete;
    }

    /*
    *  Given a list<String> (names of the Scoring calculation groups), creates and insert each of these SCG.
    */
    private List<ScoringGroup__c> saveGroups(List<ScoringGroup> scoringGroups){
        List<ScoringGroup__c> realGroupList = new List<ScoringGroup__c>();
        if( scoringGroups != null && scoringGroups.size() > 0 ){
            for(ScoringGroup sg : scoringGroups){
            	if(sg.caption != PPI_ID){
                	ScoringGroup__c newCustomScoring = new ScoringGroup__c(Caption__c = sg.caption, Survey__c = this.survey.Id);
                	realGroupList.add(newCustomScoring);
            	}
            }
            try{
                insert realGroupList;
            }
            catch(Exception e){
                this.errorGroup = true;
            }
        }
        return realGroupList ;
    }

    /*
    *    Given a list of ScoringValue object (inner Class), and a map with the form <ScoringGroup__c.Caption, ScoringGroup__c.Id>,
    *    insert each Scoring value, and relate it with the correct ScoringGroup.
    */
    private void saveScoringValues(List<ScoringValue> scoringValues, map<String, Id> mapNameIdGroup){

        List<ScoreValue__c> realScoreValues = new List<ScoreValue__c>();
        if( scoringValues != null && scoringValues.size() > 0 ){
            List<Option__c> optionsToUpdatePPIScore = new List<Option__c>();
            for(ScoringValue sv : scoringValues){
                Id idOfGroup = mapNameIdGroup.get(sv.groupName);
                Decimal realValue = ( sv.value == null || sv.value == '' ) ? 0 : decimal.valueOf(sv.value);
                if(sv.groupName == PPI_ID){
                    Option__c opt = new Option__c(id = sv.optionId,PPIScore__c = realValue);
                    optionsToUpdatePPIScore.add(opt);
                }else{
                    ScoreValue__c newCustomScoreValue = new ScoreValue__c(Option__c = sv.optionId, ScoringGroup__c = idOfGroup, Value__c = realValue );
                    realScoreValues.add(newCustomScoreValue);
                }
            }
            try{
                insert realScoreValues;
                update optionsToUpdatePPIScore;
            }
            catch(Exception e){
                this.errorValues = true;
            }
        }
    }

    /*
    *  Given a list of ScoringGroup__c, returns a map with the form: <ScoringGroup__c.Value, ScoringGroup__c.Id>.
    */
    private map<String, Id> getMapNameIdGroups(List<ScoringGroup__c> listOfGroup){

        map<String, Id> mapNameId = new map<String, Id>();
        if( listOfGroup != null && listOfGroup.size() >0 ){
            for(ScoringGroup__c sg : listOfGroup){
                mapNameId.put(sg.Caption__c, sg.Id);
            }
        }
        return mapNameId;
    }

    /*
    *  Given a parser of scoringValues, returns a List<ScoringValue>.
    */
    private List<ScoringValue> parserScoringValues(JSONParser parser){
        List<ScoringValue> listOfScoringValues = new List<ScoringValue>();
        while (parser.nextToken() != null) {
            // Start at the array of ScoringValues.
            if (parser.getCurrentToken() == JSONToken.START_ARRAY) {
                while (parser.nextToken() != null) {
                    // Advance to the start object marker to
                    if (parser.getCurrentToken() == JSONToken.START_OBJECT) {
                        // Read entire ScoringValue object
                        ScoringValue sv = (ScoringValue)parser.readValueAs(ScoringValue.class);
                        listOfScoringValues.add(sv);
                    }
                }
            }
        }
        return listOfScoringValues;
    }

    /*
    *  Given a parser of scoringGroups, returns a List<ScoringGroup> .
    */
    private List<ScoringGroup> parserScoringGroup(JSONParser parser){
        List<ScoringGroup> listOfScoringGroup = new List<ScoringGroup>();
        while (parser.nextToken() != null) {
            // Start at the array of ScoringGroup.
            if (parser.getCurrentToken() == JSONToken.START_ARRAY) {
                while (parser.nextToken() != null) {
                    // Advance to the start object marker to
                    if (parser.getCurrentToken() == JSONToken.START_OBJECT) {
                        // Read entire ScoringGroup object
                        ScoringGroup sg = (ScoringGroup)parser.readValueAs(ScoringGroup.class);
                        listOfScoringGroup.add(sg);
                    }
                }
            }
        }
        return listOfScoringGroup;
    }


    //------- Classes---------

    /*
    *  ScoringValue "home made" object
    */
    class ScoringValue {
        public String value {get;set;}
        public String optionId {get;set;}
        public String groupName {get;set;}


        public ScoringValue(ScoreValue__c source, String nameGroup){
            this.value = String.valueOf(source.Value__c);
            this.optionId = source.Option__c;
            this.groupName = nameGroup;
        }

        public ScoringValue(string pValue, String pOptionId,string pGroupName){
            this.value = pValue;
            this.optionId = pOptionId;
            this.groupName = pGroupName;
        }

    }

    /*
    *  ScoringGroup "home made" object
    */
    class ScoringGroup{
        public String caption {get;set;}
        public String id {get;set;}

        public ScoringGroup(ScoringGroup__c source){
            this.caption = source.Caption__c;
            this.id = source.Id;
        }
        public ScoringGroup(string pCaption,string pId){
        	this.caption = pCaption;
            this.id = pId;
        }
    }

    //--------------------

}