survey-salesforce/salesforce-app/src/objects/LicenseSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To block or enable functionality in the client package . Indicates whether a function is enable or if there is a limit to use it.</description>
    <fields>
        <fullName>PPI_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PPI_Editable</label>
        <type>Checkbox</type>
    </fields>
    <label>LicenseSettings</label>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of the option within the option group</description>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/SkipCondition__c.object
<CustomObject>
    <fields>
        <fullName>Condition__c</fullName>
        <description>Condition to apply to the source question value.</description>
        <label>Condition</label>
        <picklist>
            <picklistValues>
                <fullName>Answered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Is</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LesserThan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GreaterThan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InRange</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Negate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determine if the result of the evaluation must be negated (return true instead of false, and back-wise).</description>
        <label>Negate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>Question on which this condition is applied</description>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Skip Conditions</relationshipLabel>
        <relationshipName>SkipConditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SourceQuestion__c</fullName>
        <description>Question whose result will be evaluated to determine if the parent question is shown. This question must be previous to the parent question in the survey.</description>
        <label>SourceQuestion</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Affected Skip Conditions</relationshipLabel>
        <relationshipName>AffectedSkipConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value to compare against the source question value.</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Skip Condition</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Skip Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skip Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <description>This is the alias of the Survey</description>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>The ISO 3166-1 alpha-2 country code</description>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the survey is a PPI Survey</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PPIDataYear__c</fullName>
        <description>Data year for the PPI survey</description>
        <label>Data Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/classes/SurveyQuestionLogicControllerTest.cls
@isTest
private class SurveyQuestionLogicControllerTest {

//------------
// Utility
//------------


    // creates a new survey, and an instance of the controller
    // sets the current page for testing with the needed parameter
    public static SurveyQuestionLogicController getNewController(){

        Survey__c newSurvey = new Survey__c(Status__c = 'Draft'); insert newSurvey;
        Question__c section = new Question__c(Survey__c = newSurvey.Id, Caption__c = 'section', Name = 'section');insert section;
        getQuestionsList(newSurvey.Id, section.Id,'Q');
        ApexPages.StandardController stdController = new ApexPages.StandardController(newSurvey);

        PageReference currentPage = Page.SurveyQuestionLogic;
        Test.setCurrentPage(currentPage);
        currentPage.getParameters().put('id', newSurvey.Id);

        return new SurveyQuestionLogicController(stdController);
    }

  // creates a list of 5 new questions and inserts them
  // also creates options and conditions for them
  public static list<Question__c> getQuestionsList(string surveyId, string parentId,string prefix){

    list<Question__c> listReturn = new list<Question__c>();
    Question__c auxQuestion;
    for (integer i = 0; i < 5; i++){
      auxQuestion = new Question__c (Survey__c = surveyId, Caption__c = prefix + i, Name = prefix + i, Parent__c = parentId,Type__c = 'Text', Position__c = i+1);
      listReturn.add(auxQuestion);
    }
    insert listReturn;

    Option__c auxOption;
    list<Option__c> listOptions = new list<Option__c>();
    SkipCondition__c auxCondition;
    list<SkipCondition__c> listConditions = new list<SkipCondition__c>();
    for (integer i = 0; i < 5; i++){
      auxOption = new Option__c (Question__c = listReturn[i].Id, Name = prefix + i, Position__c = i+1);
      listOptions.add(auxOption);
      if (i != 0){
        auxCondition = new SkipCondition__c (Parent__c = listReturn[i].Id, SourceQuestion__c = listReturn[0].Id, Condition__c = 'Is', Negate__c = false, Value__c = 'Test');
        listConditions.add(auxCondition);
      }
    }
    insert listOptions;
    insert listConditions;

    return listReturn;
  }


//------------
// Test methods
//------------

    static testMethod void saveTest(){
        LicenseSettings__c testLicense = newLicense(false,'Test');
        insert testLicense;
        
        SurveyQuestionLogicController controller = getNewController();
    
        // test with values
        Question__c firstQuestion = [SELECT Id, Caption__c, Name, Type__c FROM Question__c][0];
        Question__c theQuestion = [SELECT Id, Caption__c, Name, Type__c FROM Question__c][2];
        string newQuestion = '[{'
            +'"id":"' + theQuestion.Id + '",'
            +'"caption":"' + theQuestion.Caption__c + '",'
            +'"type":"' + theQuestion.Type__c + '",'
            +'"options":[{"id":"a","name":"a-orig","position":"1"},{"id":"b","name":"b","position":"2"}],'
            +'"skipconditions":[{"id":"123","sourceQuestionId":"' + firstQuestion.Id + '","condition":"Is","value":"Test","negate":true},{"id":"456","sourceQuestionId":"' + firstQuestion.Id + '","condition":"Is","value":"OtherTest","negate":true}]'
            +'}]';

        PageReference currentPage = Page.SurveyQuestionLogic;
        currentPage.getParameters().put('questions', newQuestion);
        currentPage.getParameters().put('quicksave', 'true');
        Test.setCurrentPage(currentPage);

        system.assertEquals(null, controller.save());
        System.assert(!ApexPages.hasMessages(ApexPages.Severity.FATAL) && !ApexPages.hasMessages(ApexPages.Severity.ERROR));


        // test with non-draft survey
        Survey__c theSurvey = [SELECT id, Status__c FROM Survey__c];
        theSurvey.Status__c = 'Published';
        update theSurvey;
        controller.save();
        System.assert(ApexPages.hasMessages(ApexPages.Severity.FATAL) || ApexPages.hasMessages(ApexPages.Severity.ERROR));
    }

    static testMethod void checkLicense(){
        ISO_Country__c countryCode = new ISO_Country__c(Name='AA',ShortName__c='Test');
        insert countryCode;
        Survey__c survey = new Survey__c(IsPPI__c=true,CountryCode__c='AA',PPIDataYear__c = 2103);
        insert survey;
        LicenseSettings__c testLicense = newLicense(false,'Test');
        insert testLicense;
        try{
            ApexPages.Standardcontroller stdController = new ApexPages.StandardController(survey);
            SurveyQuestionLogicController extension = new SurveyQuestionLogicController(stdController);
            extension.survey.IsPPI__c=true;
        }catch(Exception e){
            system.assertEquals( system.label.SYSTEM_ERR_NOLICENSEPERMISSION, e.getMessage());   
        }
    }

    static LicenseSettings__c newLicense(Boolean PPIEditable, String licName){
        list<LicenseSettings__c> lS = [SELECT PPI_Editable__c FROM LicenseSettings__c limit 1];
        delete lS;
        LicenseSettings__c li = new LicenseSettings__c(PPI_Editable__c = PPIEditable, Name = licName);
        return li;
    }

    /**
     * This test the proper throw an error when I try to make changes in the Field mapping 
     * for this survey mean while the survey is been update.
     * This should not let me save the changes since the survey was modified.
     */
    static testMethod void testOutofSyncSaveError(){

        // PREPARE: Create a base survey that will be edited
        Survey__c survey = new Survey__c(Name='survey');
        insert survey;
        Question__c section = new Question__c(Survey__c=survey.Id,Name='section',Caption__c='section',Position__c=1,Type__c=QuestionType.QUESTION_SECTION);
        insert section;
        Question__c sourceq = new Question__c(Survey__c=survey.Id,Name='source',Parent__c=section.Id, Caption__c='source',Position__c=1,Type__c=QuestionType.QUESTION_TEXT_SHORT);
        Question__c targetq = new Question__c(Survey__c=survey.Id,Name='target',Parent__c=section.Id, Caption__c='target',Position__c=2,Type__c=QuestionType.QUESTION_TEXT_SHORT);
        insert new Question__c[]{sourceq,targetq};

        // TEST: Have someone else edit the survey, and try to edit the skip condition
        string newQuestion = '[{'
            +'"id":"' + section.Id + '",'
            +'"caption":"' + section.Caption__c + '",'
            +'"type":"' + section.Type__c + '",'
            +'"skipconditions":[]'
            +'},{'
            +'"id":"' + sourceq.Id + '",'
            +'"caption":"' + sourceq.Caption__c + '",'
            +'"type":"' + sourceq.Type__c + '",'
            +'"skipconditions":[]'
            +'},{'
            +'"id":"' + targetq.Id + '",'
            +'"caption":"' + targetq.Caption__c + '",'
            +'"type":"' + targetq.Type__c + '",'
            +'"skipconditions":['
                +'{'
                +'"id":"qwerty",'
                +'"sourceQuestionId":"' + sourceq.Id + '",'
                +'"condition":"' + QuestionType.SKIPLOGIC_CONDITION_ISANSWERED + '",'
                +'"value":"Test",'
                +'"negate":true}]'
            +'}]';

        PageReference currentPage = Page.SurveyQuestionLogic;
        currentPage.getParameters().put('id', survey.Id);
        Test.setCurrentPage(currentPage);
        SurveyQuestionLogicController controller = new SurveyQuestionLogicController(new ApexPages.StandardController(survey));

        Test.startTest();
        // Edit the survey outside the controller
        C.wait(1);
        survey = [SELECT Id, Alias__c FROM Survey__c WHERE Id = :survey.Id];
        survey.Alias__c = 'Changed';
        update survey;

        currentPage.getParameters().put('questions', newQuestion);
        currentPage.getParameters().put('quicksave', 'true');
        controller.save();
        Test.stopTest();

        // ASSERT: check that the controller was unable to save
        System.assert(ApexPages.hasMessages(ApexPages.Severity.FATAL) || ApexPages.hasMessages(ApexPages.Severity.ERROR));
    }
}