survey-salesforce/salesforce-app/src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of the option within the option group</description>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/ScoreValue__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ScoringGroup__c</fullName>
        <label>Scoring Group</label>
        <referenceTo>ScoringGroup__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Score Value</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>Score Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/ScoringGroup__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Scoring Groups</relationshipLabel>
        <relationshipName>Scoring_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Scoring Group</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scoring Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/SkipCondition__c.object
<CustomObject>
    <fields>
        <fullName>Condition__c</fullName>
        <description>Condition to apply to the source question value.</description>
        <label>Condition</label>
        <picklist>
            <picklistValues>
                <fullName>Answered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Is</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LesserThan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GreaterThan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InRange</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>Question on which this condition is applied</description>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Skip Conditions</relationshipLabel>
        <relationshipName>SkipConditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SourceQuestion__c</fullName>
        <description>Question whose result will be evaluated to determine if the parent question is shown. This question must be previous to the parent question in the survey.</description>
        <label>SourceQuestion</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Affected Skip Conditions</relationshipLabel>
        <relationshipName>AffectedSkipConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value to compare against the source question value.</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Skip Condition</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Skip Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skip Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/classes/SurveyPreviewControllerTest.cls
@isTest
public class SurveyPreviewControllerTest{

  // Test for preview controller
  static testMethod void testPreview(){

      //Set data
      Survey__c survey1 = newSurvey('FirstSurvey');
      Question__c question1 = newQuestion(survey1.Id, 'Name', 'Caption1', 1);
      Question__c question2 = newQuestion(survey1.Id, 'Name2', 'Caption2', 2);
      Option__c option1 = newOption(question1.Id, 'NameOption', 1);
      SkipCondition__c skipCondition1 = newSkipCondition(question1.Id, question2.Id, 'val1', 'Is');
      ScoringGroup__c scoringGroup1 = newScoringGroup(survey1.Id, 'captionScoring');
      ScoreValue__c scoreValue1 = newScoreValue(scoringGroup1.Id, option1.Id, 7);

      ApexPages.StandardController stdController = new ApexPages.StandardController(survey1);
      SurveyPreviewController controller = new SurveyPreviewController(stdController);
      PageReference pg = new PageReference('/apex/SurveyPreview');
      Test.setCurrentPage(pg);
      String previousPage = 'https://' + ApexPages.currentPage().getHeaders().get('Host') + '/apex/SurveyManager';
      ApexPages.currentPage().getHeaders().put('Referer', previousPage );

      controller.setDataForPreview();
      system.assertEquals( false, controller.fromNewSurvey );

      String serializedQuestions = controller.getQuestions();
      String expectedString = '[{"type":"Section","skipLogicOperator":"All","skipLogicBehavior":"Show","skipconditions"' +
                              ':[{"value":"val1","sourceQuestionId":"' + question2.Id + '","negate":false,"id":"' + skipCondition1.Id +
                              '","condition":"Is"}],"scoreValues":null,"samePage":false,"required":false,"qhint":null,"position":1,"parent":null,"options":' +
                              '[{"scoreValues":[{"value":7,"ScoringGroupId":"' + scoringGroup1.Id + '","optionId":"' + option1.Id +
                              '","id":"' + scoreValue1.Id  + '"}],"position":1,"name":"NameOption","id":"' + option1.Id + '","caption":"NameOption"}]' +
                              ',"name":"Name","minimum":null,"maximum":null,"id":"' + question1.Id +
                              '","doBefore":null,"doAfter":null,"deletedOptions":[],"currentTime":false,"caption":"Caption1"}' +
                              ',{"type":"Section","skipLogicOperator":"All","skipLogicBehavior":"Show","skipconditions":[],'+
                              '"scoreValues":null,"samePage":false,"required":false,"qhint":null,"position":2,"parent":null,"options":[],"name":"Name2","minimum":null,' +
                              '"maximum":null,"id":"' + question2.Id + '","doBefore":null,"doAfter":null,"deletedOptions":[],' +
                              '"currentTime":false,"caption":"Caption2"}]';

      system.assertEquals( expectedString  , serializedQuestions  );
  }
  //----------Utility methods------------

    static Survey__c newSurvey(String surveyName){
        Survey__c sur = new Survey__c(Status__c = 'Draft', Name = surveyName);
        insert sur;
        return sur;
    }
    static Question__c newQuestion(Id surveyId, String name, String caption, Integer position){
        Question__c question = new Question__c(Name = name, Survey__c = surveyId, Caption__c = caption, Position__c = position);
        insert question;
        return question;
    }
    static Option__c newOption(Id questionId, String name, Integer position){
        Option__c option = new Option__c(Name = name, Caption__c = name, Position__c = position, Question__c = questionId);
        insert option;
        return option;
    }

    static SkipCondition__c newSkipCondition(Id questionParent, Id questionSrc, String val, String condition){
        SkipCondition__c sc = new SkipCondition__c(Parent__c = questionParent, SourceQuestion__c = questionSrc, Value__c = val, Condition__c = condition);
        insert sc;
        return sc;
    }

    static ScoringGroup__c newScoringGroup(Id surveyId, String caption){
        ScoringGroup__c sg = new ScoringGroup__c (Survey__c = surveyId, Caption__c = caption);
        insert sg;
        return sg;
    }

    static ScoreValue__c newScoreValue( Id scoreGroupId, Id optionScoreId, Integer value ){
        ScoreValue__c sv = new ScoreValue__c (ScoringGroup__c = scoreGroupId, Option__c = optionScoreId, Value__c = value);
        insert sv;
        return sv;
    }
}