survey-salesforce/salesforce-app/src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of the option within the option group</description>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrentTime__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set date of the day and current time(take from device) as initial value</description>
        <label>Current Time</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DoAfter__c</fullName>
        <label>DoAfter</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DoBefore__c</fullName>
        <label>DoBefore</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Hint__c</fullName>
        <description>A hint for the question</description>
        <label>Hint</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Maximum__c</fullName>
        <label>Maximum</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum__c</fullName>
        <label>Minimum</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this question must be answered before moving to the next question</description>
        <inlineHelpText>Check if this question must be answered before moving to the next question</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SamePage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>All questions of a section show on same page</description>
        <label>SamePage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SkipLogicBehavior__c</fullName>
        <label>SkipLogicBehavior</label>
        <picklist>
            <picklistValues>
                <fullName>Show</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hide</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SkipLogicOperator__c</fullName>
        <label>SkipLogicOperator</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Any</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/ScoreValue__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ScoringGroup__c</fullName>
        <label>Scoring Group</label>
        <referenceTo>ScoringGroup__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Score Value</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>Score Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/ScoringGroup__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Scoring Groups</relationshipLabel>
        <relationshipName>Scoring_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Scoring Group</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scoring Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/SkipCondition__c.object
<CustomObject>
    <fields>
        <fullName>Condition__c</fullName>
        <description>Condition to apply to the source question value.</description>
        <label>Condition</label>
        <picklist>
            <picklistValues>
                <fullName>Answered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Is</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LesserThan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GreaterThan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InRange</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Negate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determine if the result of the evaluation must be negated (return true instead of false, and back-wise).</description>
        <label>Negate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>Question on which this condition is applied</description>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Skip Conditions</relationshipLabel>
        <relationshipName>SkipConditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SourceQuestion__c</fullName>
        <description>Question whose result will be evaluated to determine if the parent question is shown. This question must be previous to the parent question in the survey.</description>
        <label>SourceQuestion</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Affected Skip Conditions</relationshipLabel>
        <relationshipName>AffectedSkipConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value to compare against the source question value.</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Skip Condition</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Skip Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skip Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <description>This is the alias of the Survey</description>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Close_Message__c</fullName>
        <defaultValue>&quot;Thank you for taking the time to complete this survey!&quot;</defaultValue>
        <label>Message After Submission</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <picklist>
            <picklistValues>
                <fullName>Smartphone</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gps_Location_Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>GPS Capture</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

survey-salesforce/salesforce-app/src/classes/SurveyPreviewController.cls
public with sharing class SurveyPreviewController {

    public Survey__c survey{get; set;} // Survey to be shown.
    public Survey__c surveyPreview {get;set;}// Holds the survey to be shown as a preview.
    public boolean fromNewSurvey {get; set;} // True if called from any page except SurveyManager. (Used to render or not some attributes in the page)
    public List<ScoringGroup> scoringGroups {get;set;} //Scoring groups related to this survey.
    public string builder{get;set;}
    public SurveyPreviewController(ApexPages.StandardController stdController) {
        builder = Apexpages.currentPage().getParameters().get('b');
        this.survey = (Survey__c)stdController.getRecord();
        setDataForPreview();
        List<BuilderQuestion.ScoreValue> scoreTempList = new List<BuilderQuestion.ScoreValue>();
        Set<Id> questionsId = new Set<Id>();

        // Obtain all questions and their options, for this survey.
        for(Question__c q: [Select Id, Name, Type__c, Parent__c, Caption__c, Hint__c, Position__c,
                            Minimum__c, Maximum__c, DoBefore__c, DoAfter__c, Required__c,
                            CurrentTime__c, SkipLogicBehavior__c, SkipLogicOperator__c, SamePage__c
                            From Question__c Where Survey__c = :survey.Id]){
            sfquestions.put(q.Id, q);
            questionsId.add(q.Id);
            questions.add( new BuilderQuestion(q) );
        }
        // Obtain ScoreValues for questions selected.
        for(ScoreValue__c sv : [select Id, Option__c, Value__c, ScoringGroup__c  from ScoreValue__c
                                    where Option__r.Question__c in :questionsId order by ScoringGroup__r.CreatedDate desc ]){
            BuilderQuestion.ScoreValue newScore = new BuilderQuestion.ScoreValue(sv);
            scoreTempList.add(newScore);
        }
        // Obtain Options for the given survey.
        for(Option__c o: [Select Id, Name, Position__c,Caption__c, Question__c
                          From Option__c Where Question__r.Survey__c = :survey.Id order by position__c]){
            sfoptions.put(o.Id, o);
            BuilderQuestion bq = findQuestion(o.Question__c);
            BuilderQuestion.Option tempOption = new BuilderQuestion.Option(o);
            tempOption = addCorrectScoreValues(tempOption, scoreTempList);
            bq.options.add( tempOption );

        }
        //Obtain SkipConditions for the selected survey.
        for(SkipCondition__c c: [Select Id, Parent__c, SourceQuestion__c, Condition__c, Negate__c, Value__c
                                 From SkipCondition__c where Parent__r.Survey__c = :survey.Id]){
            findQuestion(c.Parent__c).skipconditions.add(new BuilderQuestion.SkipCondition(c));
        }

        scoringGroups = new List<ScoringGroup>();
        for(ScoringGroup__c sg : [select Id, Name, Caption__c from ScoringGroup__c where Survey__c = :survey.Id order by CreatedDate]){
            ScoringGroup newScoringGroup = new ScoringGroup(sg);
            scoringGroups.add( newScoringGroup );
        }
    }

    // Sets the preview Survey__c object and data to be shown.
    public void setDataForPreview(){
        this.fromNewSurvey = true;
        if( this.survey != null ) {
            surveyPreview = [select Id, Name, Gps_Location_Enabled__c,
                             Alias__c, Deployment__c, Close_Message__c,status__c from Survey__c where Id = :this.survey.Id ][0];
        }

        String referer = ApexPages.currentPage().getHeaders().get('Referer');

        if (referer != null){
            String lowerCaseReferer = ApexPages.currentPage().getHeaders().get('Referer').toLowerCase();
            integer refererIndex = lowerCaseReferer.indexOf('surveymanager');
            this.fromNewSurvey = (refererIndex == -1);
        }

    }

    public BuilderQuestion[] questions        = new BuilderQuestion[]{}; // Contains questions to be upserted on the next "save" call.
    public String getQuestions(){ return JSON.serialize(questions); }

        // Maps to keep correspondence between builder objects and actual Salesforce objects.
    private Map<String,Question__c> sfquestions = new Map<String,Question__c>();
    private Map<String,Option__c> sfoptions = new Map<String,Option__c>();

    // HELPER METHODS : GENERAL

    // Find a question on the list by it's id
    private BuilderQuestion findQuestion(String id) {
        for (BuilderQuestion q : questions)
            if (q.id == id)
                return q;
        return null;
    }

    /*
    *  Given a BuilderQuestion.Option, and a List of BuilderQuestion.ScoreValues, adds the related scoreValues
    *  to the given BuilderQuestion.Option.
    */
    private BuilderQuestion.Option addCorrectScoreValues(BuilderQuestion.Option opt, List<BuilderQuestion.ScoreValue> scoreList ){
        if(scoreList != null && scoreList.size() > 0){
            String idOpt = opt.Id;
            for( BuilderQuestion.ScoreValue sv : scoreList ){
                if(sv.optionId == idOpt){
                    opt.scoreValues.add(sv);
                }
            }
        }
        return opt;
    }

    public class ScoringGroup {
        public String scoringNumber {get;set;}
        public String caption {get;set;}

        public ScoringGroup(ScoringGroup__c source){
            this.scoringNumber = source.Name;
            this.caption = source.Caption__c;
        }

    }
}